name: Coveralls CI/CD
on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - run: yarn install

    coverage:
        name: Coveralls
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - run: yarn setup
            - name: Setup Temp Config File
                id: create-json
                uses: jsdaniell/create-json@1.1.2
                with:
                    name: "local.json"
                    json: ${{ secrets.CONFIG_LOCAL }}
                    dir: '/home/runner/work/rahat/rahat/config'
            - run: yarn run coverage
            - uses: coverallsapp/github-action@master
              env:
                  COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
            - run: yarn run send-coverage
